# Generated by Django 2.2.5 on 2021-06-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210620_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_vierified',
            new_name='email_verified',
        ),
    ]
